[package]
name = "hyper-microservice"
version = "0.1.0"
authors = ["full_name <xscreensaver@outlook.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
hyper = "0.12"
lazy_static = "1.0"
regex = "1.0"
slab = "0.4"

