[package]
name = "image_service"
version = "0.1.0"
authors = ["Pick1a1username <20301273+Pick1a1username@users.noreply.github.com>"]
edition = "2018"

[dependencies]
futures = "0.1.28"
hyper = "0.12"
hyper-staticfile = "0.3.1"
lazy_static = "1.0"
rand = "0.5"
regex = "1.0"
tokio = "0.1.22"
